# Generated by Django 3.0.2 on 2020-01-28 11:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Mapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerario', models.CharField(max_length=10)),
                ('location_bus', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Datos_Mapa',
                'verbose_name_plural': 'Datos_Mapas',
                'ordering': ['itinerario'],
            },
        ),
        migrations.CreateModel(
            name='Datos_Parada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_rasp_parada', models.DateTimeField()),
                ('time_created_parada', models.DateTimeField(auto_now_add=True)),
                ('siniestro_parada', models.BooleanField(default=False)),
                ('prep_asiento', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Datos_Parada',
                'verbose_name_plural': 'Datos_Paradas',
                'ordering': ['time_rasp_parada'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('location_parada', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['nombre'],
            },
        ),
    ]
